cmake_minimum_required(VERSION 3.23)
project(HelloWorld LANGUAGES C)

set(PILRC pilrc)
set(BUILD_PRC build-prc)

set(PALM_EXECUTABLE_NAME "${CMAKE_PROJECT_NAME}-PalmOS-Executable")

set(APPLICATION_NAME "Template")
set(CREATOR "Test")

file(GLOB_RECURSE EXEC_SOURCE_FILES src/*.c)
file(GLOB_RECURSE EXEC_HEADER_FILES include/*.h)

unset(CMAKE_DEPFILE_FLAGS_C)
add_executable(${PALM_EXECUTABLE_NAME})
target_sources(${PALM_EXECUTABLE_NAME}
  PRIVATE 
    ${EXEC_SOURCE_FILES}
    
  PUBLIC
    FILE_SET HEADERS
    BASE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/include
    FILES ${EXEC_HEADER_FILES}
)

set(PILRC_FLAGS -q -allowEditID -I ${CMAKE_CURRENT_SOURCE_DIR}/include -I ${CMAKE_CURRENT_SOURCE_DIR}/resources -ro)
file(GLOB_RECURSE RESOURCE_FILES resources/*.rcp)
foreach(RESOURCE_FILE IN LISTS RESOURCE_FILES)
  message("Setting up ${RESOURCE_FILE}")
  get_filename_component(RESOURCE_FILE_BASENAME ${RESOURCE_FILE} NAME_WE)
  set(RESOURCE_OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/${RESOURCE_FILE_BASENAME}.ro")
  add_custom_command(
    OUTPUT ${RESOURCE_OUTPUT_FILE}
    COMMAND ${PILRC} ${PILRC_FLAGS} -o ${RESOURCE_OUTPUT_FILE} ${RESOURCE_FILE}
    DEPENDS ${RESOURCE_FILE}
    VERBATIM
  )
  add_custom_target("Resource-${RESOURCE_FILE_BASENAME}" DEPENDS "${RESOURCE_OUTPUT_FILE}")
  add_dependencies(${PALM_EXECUTABLE_NAME} "Resource-${RESOURCE_FILE_BASENAME}")
  list(APPEND RESOURCE_OBJECTS "${CMAKE_CURRENT_BINARY_DIR}/${RESOURCE_FILE_BASENAME}.ro")
endforeach()

add_custom_command(
  OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_PROJECT_NAME}.prc
  COMMAND ${BUILD_PRC} -o ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_PROJECT_NAME}.prc -n ${APPLICATION_NAME} -c ${CREATOR} "$<TARGET_FILE:${PALM_EXECUTABLE_NAME}>" ${RESOURCE_OBJECTS}
  DEPENDS "$<TARGET_FILE:${PALM_EXECUTABLE_NAME}>" ${RESOURCE_OBJECTS}
  VERBATIM
)

add_custom_target("${CMAKE_PROJECT_NAME}-Palm-Resource-Code" ALL
  DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_PROJECT_NAME}.prc
)

